title: My Professional Site
author: Your Name
email: your.email@example.com
description: >
  Portfolio and CV of Your Name, including selected projects and blog posts.
baseurl: "/my-site"
url: "https://Jackman99.github.io"
theme: minima
